// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXAsdZv04KkPIBdLSzKcJJLGZ_7jrhEQ',
    appId: '1:599810581161:web:4d93edffd226be3c643fb8',
    messagingSenderId: '599810581161',
    projectId: 'jejuya-app',
    authDomain: 'jejuya-app.firebaseapp.com',
    storageBucket: 'jejuya-app.firebasestorage.app',
    measurementId: 'G-WYY6M6XNMG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtXAsdZv04KkPIBdLSzKcJJLGZ_7jrhEQ',
    appId: '1:599810581161:web:3ba5e68e527d38dd643fb8',
    messagingSenderId: '599810581161',
    projectId: 'jejuya-app',
    authDomain: 'jejuya-app.firebaseapp.com',
    storageBucket: 'jejuya-app.firebasestorage.app',
    measurementId: 'G-RXLG6Q1X0R',
  );
}
