final List<Map<String, dynamic>> touristLocationMockup = [
  {
    "id": 1,
    "Turn": 1,
    "CategoryEnglish": "Exhibition/Museum",
    "CategoryKorean": "자연",
    "DetailedCategoryEnglish": "Family, friends, couple, alone, indoor",
    "DetailedCategoryKorean": "산",
    "IntroductionEnglish":
        "Beyond the boundary between the everyday and the extraordinary, For Garden Door, the starting point of leaving for an unknown space.",
    "IntroductionKorean": "한라산은 대한민국에서 가장 높은 산입니다.",
    "BusinessNameEnglish": "Nohyung Supermarket",
    "BusinessNameKorean": "한라산국립공원",
    "LocationEnglish": "98 Nohyeong-ro, Jeju-si",
    "LocationKorean": "제주도 제주시",
    "Latitude": 33.4711184,
    "Longitude": 126.4610794,
    "Contact": "064-713-1888",
    "OperatingHoursEnglish": "09:00~19:00 (Last admission 18:00)",
    "OperatingHoursKorean": "24시간",
    "ClosedDaysEnglish": "Open all year round",
    "ClosedDaysKorean": "없음",
    "NoteEnglish": "Paid",
    "NoteKorean": "입장료가 있습니다.",
    "ReservationLink":
        "https://travelbox.vpass.co.kr/www/tour/search_view.html?tg_no=6044"
  },
  {
    "id": 2,
    "Turn": 2,
    "CategoryEnglish": "Exhibition/Museum",
    "CategoryKorean": "자연",
    "DetailedCategoryEnglish": "Family, friends, couple, alone, indoor",
    "DetailedCategoryKorean": "산",
    "IntroductionEnglish":
        "Beyond the boundary between the everyday and the extraordinary, For Garden Door, the starting point of leaving for an unknown space.",
    "IntroductionKorean": "한라산은 대한민국에서 가장 높은 산입니다.",
    "BusinessNameEnglish": "Nohyung Supermarket",
    "BusinessNameKorean": "한라산국립공원",
    "LocationEnglish": "98 Nohyeong-ro, Jeju-si",
    "LocationKorean": "제주도 제주시",
    "Latitude": 33.283212,
    "Longitude": 126.3499189,
    "Contact": "064-713-1888",
    "OperatingHoursEnglish": "09:00~19:00 (Last admission 18:00)",
    "OperatingHoursKorean": "24시간",
    "ClosedDaysEnglish": "Open all year round",
    "ClosedDaysKorean": "없음",
    "NoteEnglish": "Paid",
    "NoteKorean": "입장료가 있습니다.",
    "ReservationLink":
        "https://travelbox.vpass.co.kr/www/tour/search_view.html?tg_no=6044"
  },
  {
    "id": 3,
    "Turn": 3,
    "CategoryEnglish": "Exhibition/Museum",
    "CategoryKorean": "자연",
    "DetailedCategoryEnglish": "Family, friends, couple, alone, indoor",
    "DetailedCategoryKorean": "산",
    "IntroductionEnglish":
        "Beyond the boundary between the everyday and the extraordinary, For Garden Door, the starting point of leaving for an unknown space.",
    "IntroductionKorean": "한라산은 대한민국에서 가장 높은 산입니다.",
    "BusinessNameEnglish": "Nohyung Supermarket",
    "BusinessNameKorean": "한라산국립공원",
    "LocationEnglish": "98 Nohyeong-ro, Jeju-si",
    "LocationKorean": "제주도 제주시",
    "Latitude": 33.2547254,
    "Longitude": 126.3455651,
    "Contact": "064-713-1888",
    "OperatingHoursEnglish": "09:00~19:00 (Last admission 18:00)",
    "OperatingHoursKorean": "24시간",
    "ClosedDaysEnglish": "Open all year round",
    "ClosedDaysKorean": "없음",
    "NoteEnglish": "Paid",
    "NoteKorean": "입장료가 있습니다.",
    "ReservationLink":
        "https://travelbox.vpass.co.kr/www/tour/search_view.html?tg_no=6044"
  },
];
